myapp/api/E-Commerce/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('shop/',include('shop.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='shop/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/api/E-Commerce/myshop/shop/urls.py
from django.urls import path,include
from shop import views

app_name='shop'

urlpatterns = [

           path('product/<int:pk>/',views.ProductDetailView.as_view(),name='detail'),
           path('cart/<int:pk>',views.Add_To_Cart,name='add_to_cart'),
           path('cart/',views.cart,name='cart'),
           path('cart/delete/<int:pk>',views.delete_from_cart,name='delete_from_cart'),
           path('cart/delete_entire/<int:pk>',views.delete_entire,name='delete'),
           path('cart/checkout',views.checkout,name='checkout'),
           #path('cart/c',views.changecart,name='ccart'),
           path('cart/checkout/address',views.AddressCreateView.as_view(),name='form'),
           path('final',views.finalview,name='final'),
           path('category/',views.CategoryListView.as_view(),name='category'),
           path('register/',views.UserCreateView.as_view(),name='register'),
           path('category/<str:cats>',views.CategoryView,name='catlist'),
           path('profile/',views.ProfileView,name='profile'),



]

myapp/urls.py
from django.urls import path,include
from myapp import views

app_name='myapp'

urlpatterns = [

     path('create',views.ProfileCreateView.as_view(),name='create'),
     path('profile/<int:pk>/',views.ProfileDetailView.as_view(),name='detail'),
     path('profile/update/<int:pk>',views.ProfileUpdateView.as_view(),name='update'),
     path('create2',views.create_view,name='create2'),
     path('post/update/<int:id>',views.update_view,name='update2'),
     path('register',views.UserCreateView.as_view(),name='register'),
     path('post/delete/<int:id>',views.delete_view,name='update2'),
     


]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from myapp.forms import UserLoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),

    path('login/',auth_views.LoginView.as_view(template_name='myapp/login.html',authentication_form=UserLoginForm),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('accounts/', include('allauth.urls')),
    path('myapp/',include('myapp.urls')),
    path('api/',include('myapp.api.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/api/E-Commerce/myshop/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ckeditor.fields import RichTextField
import uuid
# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.user.username



class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    image = models.ImageField(blank=True,null=True,upload_to="images/")
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail',kwargs={'pk':self.pk})



class CartItem(models.Model):
    cart = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True,blank=True)
    total = models.FloatField(null=True,blank=True,default=0)
    ordered = models.BooleanField(default=False)
    transaction_id = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)


    def __str__(self):
        return str(self.id)









class Order(models.Model):
    order = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True,blank=True)
    total = models.FloatField(null=True,blank=True)
    ordered = models.BooleanField(default=False)
    transaction_id = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)
    date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return str(self.transaction_id)

class ShippingAddress(models.Model):
    customer = models.OneToOneField(User,on_delete=models.CASCADE)

    address = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    state= models.CharField(max_length=250)
    zipcode = models.PositiveIntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address
    def get_absolute_url(self):
        return reverse('shop:update',kwargs={'pk':self.pk})

myapp/api/E-Commerce/myshop/shop/forms.py
from django.contrib.auth.models import User
from django import forms
from shop.models import Customer,Product,ShippingAddress,CartItem
from django.contrib.auth.forms import UserCreationForm

class AddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields=('address','city','state','zipcode')

class UserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length = 100)
    last_name = forms.CharField(max_length = 100)

    class Meta:
        model = User
        fields = ('username','first_name','last_name')

myapp/api/E-Commerce/myshop/shop/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Customer,Product,ShippingAddress,CartItem,Order,Category
from django.contrib.auth.models import User
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.db.models import F
from shop.forms import AddressForm,UserForm
from django.contrib.auth.forms import UserCreationForm
import datetime

from django.http import HttpResponseRedirect
import random
# Create your views here.

def index(request):
    dict1 = Product.objects.annotate(odd=F('id') % 2).filter(odd=False)
    dict2 = Product.objects.annotate(odd=F('id') % 2).filter(odd=True)



    return render(request,'shop/index.html',{'products1':dict1,'products2':dict2})

class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'

def Add_To_Cart(request,pk):
    u=request.user
    p=Product.objects.all().get(id=str(pk))
    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)




    cart_item , status = CartItem.objects.get_or_create(cart=c,product=p)
    cart_item.total = cart_item.quantity * cart_item.product.price

    if status==False:

        cart_item.quantity+=1
        cart_item.total = cart_item.quantity * cart_item.product.price
        cart_item.save()






    return redirect(reverse('shop:cart'))

def cart(request):
    u=request.user

    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    ftotal = 0
    for i in cc:
        ftotal+=i.quantity * i.product.price
        i.save()



    return render(request,'shop/cart.html',{'insert':cc,'ftotal':ftotal})

def delete_from_cart(request,pk):
    u=request.user
    p=Product.objects.all().get(id=str(pk))
    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    i=CartItem.objects.all().get(cart=c,product=p)
    i.quantity=i.quantity-1
    i.total = i.quantity * i.product.price
    i.save()
    if i.quantity==0:
        i.delete()
    return redirect(reverse('shop:cart'))

def delete_entire(request,pk):
    u=request.user
    p=Product.objects.all().get(id=str(pk))
    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    i=CartItem.objects.all().get(cart=c,product=p)
    i.delete()
    return redirect(reverse('shop:cart'))

def checkout(request):
    u=request.user
    user = User.objects.get(username=u)


    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    ftotal = 0

    for i in cc:

        ftotal+=i.quantity * i.product.price




    return render(request,'shop/checkout.html',{'final':cc,'ftotal':ftotal,'user':user})




class AddressCreateView(CreateView):
    model = ShippingAddress
    form_class = AddressForm
    template_name = 'shop/address_form.html'
    success_url = reverse_lazy('shop:final')

    def form_valid(self,form):

        form.instance.customer=self.request.user
        return super().form_valid(form)
    def get_context_data(self,*args,**kwargs):
        context = super(AddressCreateView,self).get_context_data(*args,**kwargs)
        u=self.request.user
        s= ShippingAddress.objects.filter(customer__username=u).exists()
        p =ShippingAddress.objects.filter(customer__username=u)
        context['p']=p
        context['s']=s
        return context

def finalview(request):
    u=request.user

    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    ftotal = 0
    m = random.randint(14563789,24356729)

    for i in cc:
        ftotal+=i.quantity * i.product.price
        i.transaction_id = m

        i.ordered=True
        i.save()


    for new in cc:
        new_order = Order(
        order=new.cart,product=new.product,transaction_id=new.transaction_id,quantity=new.quantity,ordered=new.ordered
        )
        if new.total==0:
            new_order.total=new.product.price
        else:
             new_order.total=new.total
        new_order.save()
    cc.delete()





    return render(request,'shop/finalpage.html',{'final':cc,'ftotal':ftotal})

class AddressUpdateView(UpdateView):
    model = ShippingAddress
    template_name = 'shop/update.html'
    redirect_field_name='shop/address_form.html'
    fields = ('address','city','state','zipcode')

class AddressDetailView(DetailView):
    context_object_name='address'
    model = ShippingAddress

class CategoryListView(ListView):
    context_object_name = 'category'
    model = Category
    template_name = 'shop/shop.html'
    def get_context_data(self,*args,**kwargs):
        context = super(CategoryListView,self).get_context_data(*args,**kwargs)
        plist = Product.objects.all()
        context['plist']=plist
        return context



def CategoryView(request,cats):
    c=Category.objects.get(name=cats)
    cc = Category.objects.all()

    cats_list = Product.objects.filter(category=c)

    return render(request,'shop/categories.html',{'cats_list':cats_list,'category':cc})


class UserCreateView(CreateView):
    form_class = UserForm

    template_name = 'shop/registration.html'
    success_url = reverse_lazy('login')

def ProfileView(request):
    u=request.user

    o = Order.objects.filter(order__username=u)
    d = o[0].date

    j=Order.objects.first()
    return render(request,'shop/profile.html',{'order':o,'d':d,'j':j})

myapp/api/E-Commerce/myshop/shop/templates/shop/address_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>hii</h1>
  </body>
</html>

myapp/api/E-Commerce/myshop/shop/templates/shop/address_form.html
{% extends 'shop/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="">






{% if s == True %}
<h1>You have already entered the address</h1>
<h2>Update Address</h2>
<a href=""><button class="btn btn-primary" style="background-color:#8F00FF" type="submit" >Update Address</button></a>
<br>
<h2>OR</h2>
<a href="{% url 'shop:final' %}"><button class="btn btn-primary" style="background-color:#8F00FF" type="submit" >Place Order With Existing Address</button></a>

{% else %}
  <form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'shop:final' %}"><button class="btn btn-primary" style="background-color:#8F00FF" type="submit" >Place Order</button></a>

  </form>
{% endif %}


</div>


{% endblock %}

myapp/api/E-Commerce/myshop/shop/templates/shop/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Shoppers</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/ow.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">


    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>

  </head>
  <body>

  <div class="site-wrap">
    <header class="site-navbar" role="banner">
      <div class="site-navbar-top">
        <div class="container">
          <div class="row align-items-center">

            <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
              <form action="" class="site-block-top-search">
                <span class="icon icon-search2"></span>
                <input type="text" class="form-control border-0" placeholder="Search">
              </form>
            </div>

            <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
              <div class="site-logo">
                <a href="index.html" class="js-logo-clone">Shoppers</a>
              </div>
            </div>

            <div class="col-6 col-md-4 order-3 order-md-3 text-right">
              <div class="site-top-icons">
                <ul>
                  <li><a href="#"><span class="icon icon-person"></span></a></li>
                  <li><a href="#"><span class="icon icon-heart-o"></span></a></li>
                  <li>
                    <a href="{% url 'shop:cart' %}" class="site-cart">
                      <span class="icon icon-shopping_cart"></span>
                      <span class="count">CART</span>
                    </a>
                  </li>
                  <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <nav class="site-navigation text-right text-md-center" role="navigation">
        <div class="container">
          <ul class="site-menu js-clone-nav d-none d-md-block">
            <li class="has-children active">
              <a href="{% url 'index' %}">Home</a>

            </li>
            <li class="has-children">
              <a href="about.html">About</a>

            </li>
            <li><a href="shop.html">Shop</a></li>
            <li><a href="{% url 'shop:category' %}">Categories</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'shop:profile' %}">My Orders</a></li>
            {% endif %}
            <li><a href="contact.html">Contact</a></li>
            <li class="has-children">
              <a href="about.html">Settings</a>
              <ul class="dropdown">
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
                <li><a href="{% url 'shop:register' %}">Register</a></li>

              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>

     <div class="container">
      {% block body_block %}
      {% endblock %}
     </div>
     <footer class="site-footer border-top">
       <div class="container">
         <div class="row">
           <div class="col-lg-6 mb-5 mb-lg-0">
             <div class="row">
               <div class="col-md-12">
                 <h3 class="footer-heading mb-4">Navigations</h3>
               </div>
               <div class="col-md-6 col-lg-4">
                 <ul class="list-unstyled">
                   <li><a href="{% url 'shop:category' %}">Categories</a></li>
                   <li><a href="{% url 'shop:catlist' cats='Electronics' %}">Electronics</a></li>
                   <li><a href="{% url 'shop:catlist' cats='Footwear' %}">Footwear</a></li>
                   <li><a href="{% url 'shop:catlist' cats='Books' %}">Books</a></li>
                   <li><a href="{% url 'shop:catlist' cats='Clothes' %}">Clothes</a></li>
                 </ul>
               </div>
               <div class="col-md-6 col-lg-4">
                 <ul class="list-unstyled">
                   <li><a href="{% url 'shop:profile' %}">My Orders</a></li>
                   <li><a href="{% url 'shop:cart' %}">Cart</a></li>
                   <li><a href="#">About</a></li>
                 </ul>
               </div>

             </div>
           </div>
           <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
             <h3 class="footer-heading mb-4">Our Top Product</h3>
             <a href="#" class="block-6">
               <img src="media/images/shoes.jpg" alt="Image placeholder" class="img-fluid rounded mb-4">
               <h3 class="font-weight-light  mb-0">Finding Your Perfect Shoes</h3>
               <p>Promo from  nuary 15 &mdash; 25, 2019</p>
             </a>
           </div>
           <div class="col-md-6 col-lg-3">
             <div class="block-5 mb-5">
               <h3 class="footer-heading mb-4">Contact Info</h3>
               <ul class="list-unstyled">
                 <li class="address">203 Gandhi Road, SB Colony, Gurgaon, Delhi, India</li>
                 <li class="phone"><a href="tel://23923929210">8104587916</a></li>
                 <li class="email">emailaddress@domain.com</li>
               </ul>
             </div>

             <div class="block-7">
               <form action="#" method="post">
                 <label for="email_subscribe" class="footer-heading">Subscribe</label>
                 <div class="form-group">
                   <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
                   <input type="submit" class="btn btn-sm btn-primary" value="Send">
                 </div>
               </form>
             </div>
           </div>
         </div>


         </div>
       </div>
     </footer>
    </body>

myapp/api/E-Commerce/myshop/shop/templates/shop/cart.html
{% extends 'shop/base.html' %}

{% block body_block %}
<div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <form class="col-md-12" method="post">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="product-thumbnail">Image</th>
                    <th class="product-name">Product</th>
                    <th class="product-price">Price</th>
                    <th class="product-quantity">Quantity</th>
                    <th class="product-total">Total</th>
                    <th class="product-remove">Remove</th>
                  </tr>
                </thead>

                <tbody>
                  {% for i in insert %}
                  {% if i.ordered == False %}

                  <tr>
                    <td class="product-thumbnail">
                      <img src="{{i.product.image.url}}" alt="Image" class="img-fluid">
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">{{i.product.name}}</h2>
                    </td>
                    <td>{{i.product.price}} </td>
                    <td>
                      <div class="input-group mb-3" style="max-width: 120px;">
                        <div class="input-group-prepend">
                          <button class="btn btn-outline-primary js-btn-minus" type="button"><a href="{% url 'shop:delete_from_cart' pk=i.product.pk %}">&minus;</a></button>
                        </div>
                        <input type="text" class="form-control text-center" value={{i.quantity}} placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                        <div class="input-group-append">
                          <button  class="btn btn-outline-primary js-btn-plus" type="button"><a href="{% url 'shop:add_to_cart' pk=i.product.pk %}">&plus;</a></button>

                        </div>
                      </div>

                    </td>

                    <td>
                         {% if i.total == 0 %}
                         {{i.product.price}}
                         {% else %}
                         {{i.total}}
                         {% endif %}
                    </td>
                    <td><a href="{% url 'shop:delete' pk=i.product.pk %}" class="btn btn-primary btn-sm">X</a></td>

                  </tr>
                  {% endif %}


                  {% endfor %}
                </tbody>
              </table>
            </div>
          </form>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6 mb-3 mb-md-0">
                <button class="btn btn-primary btn-sm btn-block">Update Cart</button>
              </div>
              <div class="col-md-6">
                <a href="{% url 'index' %}"><button class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</button></a>
              </div>
            </div>
            <div class="row">
            
            </div>
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                  </div>
                </div>

                <div class="row mb-5">
                  <div class="col-md-6">
                    <span class="text-black">Total</span>
                  </div>
                  <div class="col-md-6 text-right">

                      {% if insert.ordered == False %}

                    <strong class="text-black">{{ftotal}}</strong>
                      {% endif %}


                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12">

                    {% if insert.ordered == False %}
                    <a href="{% url 'shop:checkout' %}"><button class="btn btn-primary btn-lg py-3 btn-block" ">Proceed To Checkout</button></a>
                    {% else %}
                    <button class="btn btn-primary btn-lg py-3 btn-block" ">Your cart is empty</button>
                    {% endif %}


                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

myapp/api/E-Commerce/myshop/shop/templates/shop/categories.html
{% extends 'shop/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="container">
<div class="row">
<div class="col-3">
  <div class="border p-4 rounded mb-4">
    <a href="{% url 'shop:category' %}"><h2 class="mb-3 h6 text-uppercase text-black d-block">Show All</h2></a>
              <h3 class="mb-3 h6 text-uppercase text-black d-block">Categories</h3>
              <ul class="list-unstyled mb-0">
                {% for i in category %}
                <li class="mb-1"><a href="{% url 'shop:catlist' cats=i.name %}" class="d-flex"><span>{{i.name}}</span> <span class="text-black ml-auto"></span></a></li>
               {% endfor %}
              </ul>
            </div>
</div>
<div class="col-9">
  <div class="row">
    {% for p in cats_list %}
    <div class="col-4">
      <div class="block-4 text-center border">
        <figure class="block-4-image">
          <a href="shop-single.html"><img src="{{p.image.url}}" alt="Image placeholder" class="img-fluid"></a>
        </figure>
        <div class="block-4-text p-4">
          <h3><a href="shop-single.html">{{p.name}}</a></h3>
          <p class="mb-0">Finding perfect products</p>
          <p class="text-primary font-weight-bold">{{p.price}}</p>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>


              </div>
</div>

</div>


{% endblock %}

myapp/api/E-Commerce/myshop/shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}

{% block body_block %}
<div class="bg-light py-3">
     <div class="container">
       <div class="row">
         <div class="col-md-12 mb-0"><a href="{% url 'index' %}">Home</a> <span class="mx-2 mb-0">/</span> <a href="{% url 'shop:cart' %}">Cart</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Checkout</strong></div>
       </div>
     </div>
   </div>

   <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6">

            <h2 class="h3 mb-3 text-black">Customer Details</h2>
            <div class="p-3 p-lg-5 border">

            <table class="table site-block-order-table mb-5">
              <thead>
                <th>Name</th>
                <th>Email</th>
              </thead>
              <tbody>


                <tr>
                  <td> <strong class="mx-2"></strong> {{user.username}}</td>
                  <td>
                    {{user.email}}
                  </td>
                </tr>




            </table>
            </div>

        </div>




              <div class="col-md-6">
                <h2 class="h3 mb-3 text-black">Your Order</h2>
                <div class="p-3 p-lg-5 border">
                  <table class="table site-block-order-table mb-5">
                    <thead>
                      <th>Product</th>
                      <th>Total</th>
                    </thead>
                    <tbody>
                      {% for i in final %}
                      {% if i.ordered == False %}

                      <tr>
                        <td>{{i.product.name}} <strong class="mx-2">x</strong> {{i.quantity}}</td>
                        <td>
                          {% if i.total == 0 %}
                          {{i.product.price}}
                          {% else %}
                          {{i.total}}
                          {% endif %}
                        </td>
                      </tr>
                        {% endif %}
                      {% endfor %}



                      <tr>


                        <td class="text-black font-weight-bold"><strong>Order Total</strong></td>
                        <td class="text-black font-weight-bold"><strong>{{ftotal}}</strong></td>

                      </tr>
                    </tbody>
                  </table>





                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="form-group">
          <a href="{% url 'shop:form' %}"><button class="btn btn-primary btn-md py-3 btn-block">Place Order</button></a>
        </div>

      </div>
    </div>

{% endblock %}

myapp/api/E-Commerce/myshop/shop/templates/shop/shop.html
{% extends 'shop/base.html' %}
{% load staticfiles %}

{% block body_block %}


<div class="container">
<div class="row">
<div class="col-3">
  <div class="border p-4 rounded mb-4">
              <a href="{% url 'shop:category' %}"><h2 class="mb-3 h6 text-uppercase text-black d-block">Show All</h2></a>  
              <h3 class="mb-3 h6 text-uppercase text-black d-block">Categories</h3>
              <ul class="list-unstyled mb-0">
                {% for i in category %}
                <li class="mb-1"><a href="{% url 'shop:catlist' cats='Electronics' %}" class="d-flex"><span>{{i.name}}</span> <span class="text-black ml-auto"></span></a></li>
               {% endfor %}
              </ul>
            </div>
</div>
<div class="col-9">
  <div class="row">
    {% for p in plist %}
    <div class="col-4">
      <div class="block-4 text-center border">
        <figure class="block-4-image">
          <a href="shop-single.html"><img src="{{p.image.url}}" alt="Image placeholder" class="img-fluid"></a>
        </figure>
        <div class="block-4-text p-4">
          <h3><a href="shop-single.html">{{p.name}}</a></h3>
          <p class="mb-0">Finding perfect products</p>
          <p class="text-primary font-weight-bold">{{p.price}}</p>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>


              </div>
</div>

</div>

{% endblock %}