myapp/api/E-Commerce/myshop/shop/urls.py
from django.urls import path,include
from shop import views

app_name='shop'

urlpatterns = [

           path('product/<int:pk>/',views.ProductDetailView.as_view(),name='detail'),
           path('cart/<int:pk>',views.Add_To_Cart,name='add_to_cart'),
           path('cart/',views.cart,name='cart'),
           path('cart/delete/<int:pk>',views.delete_from_cart,name='delete_from_cart'),
           path('cart/delete_entire/<int:pk>',views.delete_entire,name='delete'),
           path('cart/checkout',views.checkout,name='checkout'),
           #path('cart/c',views.changecart,name='ccart'),
           path('cart/checkout/address',views.AddressCreateView.as_view(),name='form'),
           path('final',views.finalview,name='final'),
           path('category/',views.CategoryListView.as_view(),name='category'),
           path('register/',views.UserCreateView.as_view(),name='register'),
           path('category/<str:cats>',views.CategoryView,name='catlist'),
           path('profile/',views.ProfileView,name='profile'),



]

myapp/api/urls.py
from django.urls import path
from myapp.api import views

app_name:'myapp'

urlpatterns = [

    path('generic/profile/',views.GenericAPIView.as_view()),
    path('generic/profile/<int:pk>/',views.GenericAPIView.as_view()),
    path('post/',views.post_list),
    path('post/<int:pk>',views.post_detail),

]

myapp/urls.py
from django.urls import path,include
from myapp import views

app_name='myapp'

urlpatterns = [

     path('create',views.ProfileCreateView.as_view(),name='create'),
     path('profile/<int:pk>/',views.ProfileDetailView.as_view(),name='detail'),
     path('profile/update/<int:pk>',views.ProfileUpdateView.as_view(),name='update'),
     path('create2',views.create_view,name='create2'),
     path('post/update/<int:id>',views.update_view,name='update2'),
     path('register',views.UserCreateView.as_view(),name='register'),
     path('post/delete/<int:id>',views.delete_view,name='update2'),
     


]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from myapp.forms import UserLoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),

    path('login/',auth_views.LoginView.as_view(template_name='myapp/login.html',authentication_form=UserLoginForm),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('accounts/', include('allauth.urls')),
    path('myapp/',include('myapp.urls')),
    path('api/',include('myapp.api.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/api/E-Commerce/myshop/shop/forms.py
from django.contrib.auth.models import User
from django import forms
from shop.models import Customer,Product,ShippingAddress,CartItem
from django.contrib.auth.forms import UserCreationForm

class AddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields=('address','city','state','zipcode')

class UserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length = 100)
    last_name = forms.CharField(max_length = 100)

    class Meta:
        model = User
        fields = ('username','first_name','last_name')

myapp/forms.py
from django import forms
from myapp.models import Profile,Post
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

class ProfileForm(forms.ModelForm):
    class Meta:
        
        model = Profile
        fields = ('name','surname','bio','profile_image','city','country','age')

class PostForm(forms.ModelForm):
    class Meta:
        model =Post
        fields = ('image','name')

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input",
        "type": "text",
        "placeholder": "enter username"
    }))

    password = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input",
        "type": "password",
        "placeholder": "enter password"
    }))


class UserForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input",
        "type": "text",
        "placeholder": "enter username"
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input",
        "type": "email",
        "placeholder": "enter email-id"
    }))

    password1 = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input",
        "type": "password",
        "placeholder": "enter password"
    }))

    password2 = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input",
        "type": "password",
        "placeholder": "re-enter password"
    }))

    class Meta:
        model = User
        fields = ('username','email', 'password1', "password2")

myapp/api/E-Commerce/myshop/shop/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Customer,Product,ShippingAddress,CartItem,Order,Category
from django.contrib.auth.models import User
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.db.models import F
from shop.forms import AddressForm,UserForm
from django.contrib.auth.forms import UserCreationForm
import datetime

from django.http import HttpResponseRedirect
import random
# Create your views here.

def index(request):
    dict1 = Product.objects.annotate(odd=F('id') % 2).filter(odd=False)
    dict2 = Product.objects.annotate(odd=F('id') % 2).filter(odd=True)



    return render(request,'shop/index.html',{'products1':dict1,'products2':dict2})

class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'

def Add_To_Cart(request,pk):
    u=request.user
    p=Product.objects.all().get(id=str(pk))
    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)




    cart_item , status = CartItem.objects.get_or_create(cart=c,product=p)
    cart_item.total = cart_item.quantity * cart_item.product.price

    if status==False:

        cart_item.quantity+=1
        cart_item.total = cart_item.quantity * cart_item.product.price
        cart_item.save()






    return redirect(reverse('shop:cart'))

def cart(request):
    u=request.user

    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    ftotal = 0
    for i in cc:
        ftotal+=i.quantity * i.product.price
        i.save()



    return render(request,'shop/cart.html',{'insert':cc,'ftotal':ftotal})

def delete_from_cart(request,pk):
    u=request.user
    p=Product.objects.all().get(id=str(pk))
    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    i=CartItem.objects.all().get(cart=c,product=p)
    i.quantity=i.quantity-1
    i.total = i.quantity * i.product.price
    i.save()
    if i.quantity==0:
        i.delete()
    return redirect(reverse('shop:cart'))

def delete_entire(request,pk):
    u=request.user
    p=Product.objects.all().get(id=str(pk))
    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    i=CartItem.objects.all().get(cart=c,product=p)
    i.delete()
    return redirect(reverse('shop:cart'))

def checkout(request):
    u=request.user
    user = User.objects.get(username=u)


    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    ftotal = 0

    for i in cc:

        ftotal+=i.quantity * i.product.price




    return render(request,'shop/checkout.html',{'final':cc,'ftotal':ftotal,'user':user})




class AddressCreateView(CreateView):
    model = ShippingAddress
    form_class = AddressForm
    template_name = 'shop/address_form.html'
    success_url = reverse_lazy('shop:final')

    def form_valid(self,form):

        form.instance.customer=self.request.user
        return super().form_valid(form)
    def get_context_data(self,*args,**kwargs):
        context = super(AddressCreateView,self).get_context_data(*args,**kwargs)
        u=self.request.user
        s= ShippingAddress.objects.filter(customer__username=u).exists()
        p =ShippingAddress.objects.filter(customer__username=u)
        context['p']=p
        context['s']=s
        return context

def finalview(request):
    u=request.user

    c=User.objects.get(username=u)
    cc=CartItem.objects.filter(cart=c)
    ftotal = 0
    m = random.randint(14563789,24356729)

    for i in cc:
        ftotal+=i.quantity * i.product.price
        i.transaction_id = m

        i.ordered=True
        i.save()


    for new in cc:
        new_order = Order(
        order=new.cart,product=new.product,transaction_id=new.transaction_id,quantity=new.quantity,ordered=new.ordered
        )
        if new.total==0:
            new_order.total=new.product.price
        else:
             new_order.total=new.total
        new_order.save()
    cc.delete()





    return render(request,'shop/finalpage.html',{'final':cc,'ftotal':ftotal})

class AddressUpdateView(UpdateView):
    model = ShippingAddress
    template_name = 'shop/update.html'
    redirect_field_name='shop/address_form.html'
    fields = ('address','city','state','zipcode')

class AddressDetailView(DetailView):
    context_object_name='address'
    model = ShippingAddress

class CategoryListView(ListView):
    context_object_name = 'category'
    model = Category
    template_name = 'shop/shop.html'
    def get_context_data(self,*args,**kwargs):
        context = super(CategoryListView,self).get_context_data(*args,**kwargs)
        plist = Product.objects.all()
        context['plist']=plist
        return context



def CategoryView(request,cats):
    c=Category.objects.get(name=cats)
    cc = Category.objects.all()

    cats_list = Product.objects.filter(category=c)

    return render(request,'shop/categories.html',{'cats_list':cats_list,'category':cc})


class UserCreateView(CreateView):
    form_class = UserForm

    template_name = 'shop/registration.html'
    success_url = reverse_lazy('login')

def ProfileView(request):
    u=request.user

    o = Order.objects.filter(order__username=u)
    d = o[0].date

    j=Order.objects.first()
    return render(request,'shop/profile.html',{'order':o,'d':d,'j':j})

myapp/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.filters import SearchFilter,OrderingFilter

from django.contrib.auth.models import User
from myapp.models import *
from myapp.api.serializers import ProfileSerializer,PostSerializer
from rest_framework.authtoken.models import Token
from rest_framework.pagination import PageNumberPagination
from rest_framework import generics
from rest_framework import mixins

class GenericAPIView(generics.GenericAPIView, mixins.ListModelMixin, mixins.CreateModelMixin,
                     mixins.UpdateModelMixin, mixins.RetrieveModelMixin,
                     mixins.DestroyModelMixin):

    serializer_class = ProfileSerializer
    queryset = Profile.objects.all()
    lookup_field = 'pk'

    def get(self,request,pk=None):
        if pk:
            return self.retrieve(request)
        else:
            return self.list(request)

    @permission_classes((IsAuthenticated,))

    def post(self, request):
        return self.create(request)

    @permission_classes((IsAuthenticated,))

    def put(self, request, pk=None):
        return self.update(request, pk)

    @permission_classes((IsAuthenticated,))

    def delete(self, request, pk=None):
        return self.destroy(request, pk)


@api_view(['GET','POST'])
@permission_classes((IsAuthenticated,))
def post_list(request):
    if request.method == 'GET':
        posts = Post.objects.all()
        serializer = PostSerializer(posts,many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = PostSerializer(posts,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)

        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET','PUT','DELETE'])
@permission_classes((IsAuthenticated,))
def post_detail(request,pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    user =request.user
    if post.user!=user:
        return Response({'response':'You are not authorized to edit this post'})
    if request.method == 'GET':
        serializer = PostSerializer(post)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = PostSerializer(post,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)

        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        post.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

myapp/views.py
from django.shortcuts import render,get_object_or_404
from myapp.models import Profile,Post
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from myapp.forms import ProfileForm,PostForm,UserForm
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        u = User.objects.get(username=request.user)
        if Profile.objects.filter(user__username=u).exists():
            p = Profile.objects.get(user__username=u)
        else:
            p=1

        pp = Profile.objects.all()







        return render(request,'myapp/index.html',{'myprofile':p,'u':u,'profilejay':pp})
    else:
        return render(request,'myapp/index.html')




class ProfileCreateView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    form_class=ProfileForm
    model = Profile

    def form_valid(self,form):
        form.instance.user=self.request.user
        return super().form_valid(form)



class ProfileDetailView(LoginRequiredMixin,DetailView):
    context_object_name = 'profile'
    model = Profile




    def get_context_data(self,*args,**kwargs):
        context = super(ProfileDetailView,self).get_context_data(*args,**kwargs)
        p=Profile.objects.get(id=self.kwargs['pk'])


        jay=p.user.id
        aa = Post.objects.filter(user_id=jay)

        context['aa'] = aa
        return context

class ProfileUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    model = Profile
    redirect_field_name='myapp/profile_detail.html'
    fields = ('name','surname','bio','profile_image','city','country','age')



def create_view(request):
    # dictionary for initial data with
    # field names as keys
    context ={}
    u=User.objects.get(username=request.user)
    aa=u.profile.id

    # add the dictionary during initialization
    form = PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():

        f=form.save(commit=False)
        f.user=u
        f.save()
        return HttpResponseRedirect(reverse('myapp:detail',args=[aa]))

    context['form']= form
    return render(request, "myapp/post_form.html", context)





def update_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context ={}

    # fetch the object related to passed id
    obj = get_object_or_404(Post, id = id)
    p=Post.objects.get(id=id)
    pp=p.user.profile.id

    # pass the object as instance in form
    form = PostForm(request.POST or None,request.FILES or None, instance = obj)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('myapp:detail',args=[pp]))

    # add form dictionary to context
    context["form"] = form

    return render(request, "myapp/post_form.html", context)

class UserCreateView(CreateView):
    form_class = UserForm

    template_name = 'myapp/registration.html'
    success_url = reverse_lazy('login')

def delete_view(request,id):
    p=Post.objects.get(id=id)
    pp=p.user.profile.id
    obj = get_object_or_404(Post, id = id)
    obj.delete()

    return HttpResponseRedirect(reverse('myapp:detail',args=[pp]))

myapp/templates/myapp/login.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
      *{
        font-family: 'Quicksand', sans-serif;
      }
    </style>
  </head>
  <body>
    <nav class="navbar is-black" role="navigation" aria-label="main navigation">


      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a href="{% url 'index' %}" class="navbar-item">
            Home
          </a>
        </div>


      </nav>

    <!--new form-->
    <section class="hero is-dark is-fullheight">
      <div class="hero-body header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 600px; background-image:url({% static 'images/2.jpg' %}); background-size: cover; background-position: center top;page-break-inside: avoid;">
        <div class="container">
          <div class="columns is-centered">

            <div class="column is-5-tablet is-4-desktop is-3-widescreen">
              <form method="POST" action="." class="box">
                {% csrf_token %}

                <h1 class="has-text-centered mb-5 is-size-3">Login</h1>

                <div class="field">
                  <label for="" class="label">Username</label>
                  <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left">
                      <i class="fa fa-user"></i>
                    </span>
                  </div>
                </div>

                <div class="field">
                  <label for="" class="label">Password</label>
                  <div class="control has-icons-left">
                    {{ form.password }}
                    <span class="icon is-small is-left">
                      <i class="fa fa-lock"></i>
                    </span>
                  </div>
                </div>



                <div class="field">
                  <button class="button is-success" type="submit">
                    Login
                  </button>
                </div>
                <div class="field">
                  Need account ? <a href="{% url 'myapp:register' %}">Signup</a>
                </div>
                <h3>OR</h3>
                  <a href="{% provider_login_url 'google' %}">Login with Google</a>
              </form>

            </div>
          </div>
        </div>
      </div>
    </section>
 </body>
</html>

myapp/templates/myapp/profile_detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/myapp.css' %}">
  </head>


<body>
  <div class="main-content">
    <!-- Top navbar -->
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
      <div class="container-fluid">
        <!-- Brand -->
        <a href="{% url 'myapp:detail' pk=request.user.profile.pk %}" class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block">User profile</a>
        <!-- Form -->
        <span  class="mb-0 text-sm  font-weight-bold"><a style="color:white" href="{% url 'logout' %}">Logout</a></span>
        <span  class="mb-0 text-sm  font-weight-bold"><a style="color:white" href="{% url 'index' %}">Home</span>
        <!-- User -->
        <ul class="navbar-nav align-items-center d-none d-md-flex">
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                  {% if not profile.profile_image  %}
                  <img src="https://demos.creative-tim.com/argon-dashboard/assets/img/theme/team-4.jpg" alt="">
                  {% else %}
                  <img alt="Image placeholder" src="{{ profile.profile_image.url }}">
                  {% endif %}
                </span>
                <div class="media-body ml-2 d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">{{request.user}}</span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
              <div class=" dropdown-header noti-title">
                <h6 class="text-overflow m-0">Welcome!</h6>
              </div>
              <a href="../examples/profile.html" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>My profile</span>
              </a>
              <a href="../examples/profile.html" class="dropdown-item">
                <i class="ni ni-settings-gear-65"></i>
                <span>Settings</span>
              </a>
              <a href="../examples/profile.html" class="dropdown-item">
                <i class="ni ni-calendar-grid-58"></i>
                <span>Activity</span>
              </a>
              <a href="../examples/profile.html" class="dropdown-item">
                <i class="ni ni-support-16"></i>
                <span>Support</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#!" class="dropdown-item">
                <i class="ni ni-user-run"></i>
                <span>Logout</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 600px; background-image: url({% static 'images/downloadjay.jpg' %}); background-size: cover; background-position: center top;">
      <!-- Mask -->
      <span class="mask bg-gradient-default opacity-8"></span>
      <!-- Header container -->
      <div class="container-fluid d-flex align-items-center">
        <div class="row">
          <div class="col-lg-7 col-md-10">

            {% if profile.user == request.user %}
            <h1 class="display-2 text-white">Hello {{profile.name}} {{profile.surname}}</h1>
            <p class="text-white mt-0 mb-5">This is your profile page. You can upload and delete posts and edit your profile</p>
            <a href="{% url 'myapp:update' pk=profile.pk %}"><input class="btn btn-primary" style="background-color:#8F00FF" type="submit" name="" value="Update Profile"></a>

            {% else %}
            <h1 class="display-2 text-white">Welcome to {{profile.name}} {{profile.surname}}'s Profile Page</h1>
            {% endif %}

          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--7">
      <div class="row">
        <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
          <div class="card card-profile shadow">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-profile-image">
                  <a href="#">
                    {% if not profile.profile_image %}
                    <img src="https://demos.creative-tim.com/argon-dashboard/assets/img/theme/team-4.jpg" alt="">
                    {% else %}
                    <img src="{{ profile.profile_image.url }}" class="">
                    {% endif %}
                  </a>
                </div>
              </div>
            </div>
            <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
              <div class="d-flex justify-content-between">
                {% if profile.user == request.user %}
                <a href="{% url 'myapp:update' pk=profile.pk %}" class="btn btn-sm btn-info mr-4">Edit</a>
                {% endif %}
              </div>
            </div>
            <div class="card-body pt-0 pt-md-4">
              <div class="row">
                <div class="col">
                  <div class="card-profile-stats d-flex justify-content-center mt-md-5">

                    <div>
                      <span class="heading">{{aa.count}}</span>
                      <span class="description">Photos</span>
                    </div>


                  </div>
                </div>
              </div>
              <div class="text-center">
                <h3>
                  {{profile.name}} {{profile.surname}}<span class="font-weight-light">, {{profile.age}}</span>
                </h3>
                <h4>
                  {{profile.city}},{{profile.country}}
                </h4>

                <hr class="my-4">
                <h3>Bio</h3>
                <p>{{profile.bio}}</p>

                <a href="#">Show more</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-8 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">{{profile.name}}'s account</h3>
                </div>
                <div class="col-4 text-right">
                  <a href="#!" class="btn btn-sm btn-primary">Settings</a>
                </div>
              </div>
            </div>
            <div class="card-body">

                <h6 class="heading-small text-muted mb-4">User information</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-username">Username</label>
                        <br>{{profile.user.username}}
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Email address</label>
                        <br>{{profile.user.email}}
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-first-name">First name</label>
                        <br>{{profile.name}}
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        <label class="form-control-label" for="input-last-name">Last name</label>
                        <br>{{profile.surname}}
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4">
                <!-- Address -->
                  {% if profile.user == request.user %}
                  <a href="{% url 'myapp:create2' %}"><input class="btn btn-sm btn-primary"  type="submit" name="" value="Create Posts"></a>
                  {% endif %}

                <h6 class="heading-small text-muted mb-4">Posts</h6>

                <br>
                <div class="pl-lg-4">
                  <div class="row">
                    {% for i in aa %}

                    <div style='height:300px' class="col-sm-4">



                          <div class="card-profile-image">

                            <img style='max-height:300px' class="rounded " src="{{ i.image.url }}" alt="">


                          </div>
                          <br>
                            {% if profile.user == request.user %}
                             <a href="{% url 'myapp:update2' id=i.pk %}"><span><p>&#10008</p></span></a>
                            {% endif %}





                    </div>
                    {% endfor %}
                </div>


            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

  <footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6 m-auto text-center">
        <div class="copyright">
          <p>Made with <a href="https://www.creative-tim.com/product/argon-dashboard" target="_blank">Argon Dashboard</a> by Creative Tim</p>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>